server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgres://postgresql:87ItpkPHePWv20TcKtDGWaK2Q2scepUk@dpg-cngubqgl6cac73ajnelg-a/exampledb_lqrm
    username: postgresql
    password: 87ItpkPHePWv20TcKtDGWaK2Q2scepUk
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgresSQLDialect
